Accessibility
RicardoEgas/MyPortfolio pull request #7
Opened 2023-04-11 14:00 UTC by RicardoEgas

We checked the accessibility for this project webpage and changed the following to meet the requirements:

- We changed the title's name to something more specific;
- We made some modifications to some of the images'  "alt" to avoid unnecessary descriptions;
- Added "for" attribute to the labels tags;

 We did not encounter any issue with all the other accessibility tests we made.

2023-04-11 14:42 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/4WFFDhSWjNfa63W8sW/giphy.gif)


# Hi @RicardoEgas 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- You just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 14:42 UTC, AbelG101 commented on index.html
- Great job determining changes in your Portfolio 👏 however you need to make some changes as requested in the project requirement.
    - [ ] As specified in the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/6_accessability.md) you have to make a report on your PR description listing all the points you have covered. Check out the example below:
    - ```
      ...
      Page titles - no issues found
      Image text alternatives - issues found
      [link to the corresponding line of code/s]
      ...
       ```
     - [ ] Once again as specified in the project requirements please make sure to link to the corresponding line of code ([here's how](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148)) where the changes are required in your PR description. 
     ![firefox_Qld0tf4cYR](https://user-images.githubusercontent.com/104968236/231188168-e3028e71-c243-4c39-894d-22e66ec8cc48.png)

2023-04-12 14:10 UTC, LionRouge1 approved these changes
Hi @RicardoEgas, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

![done](https://media.giphy.com/media/a5llhdWKMOIfneMCpB/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-12 14:43 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @RicardoEgas, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 15:14 UTC, merged